### ISSUE TITLE
Fails to assign milestone

### ISSUE THREAD

**Issue by vadi2** [zoispag/action-assign-milestone#55]
The action doesn't actually assign pull requests to milestones and there's few warnings when running it -

```
(node:1763) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/zoispag/action-assign-milestone/v1/webpack:/action-assign-milestone/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1763) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zoispag** [comment]
Hey @vadi2.

Thanks for reporting the issue.

It does work for me, see:

![image](https://user-images.githubusercontent.com/21138205/150321604-315cb12e-1d4a-477c-b7d0-ebcbb008153e.png)

but indeed, does not work for PRs originated by dependabot (which used to work as well).

Is this PR created by a user marked as bot by GitHub?

**Comment by vadi2** [comment]
It's created by a user, though I'm also committing the workflow itself in the same PR. Maybe that is it

**Comment by zoispag** [comment]
> It's created by a user, though I'm also committing the workflow itself in the same PR. Maybe that is it

Ah, it is possible that this is the reason. I know GitHub changed something recently and it stopped working for me for PRs made by dependabot. Let me know if it works when the workflow is already committed.
